//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BdSofts_WebApi_Auth_Blood.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdSofts_WebApi_Auth_Blood_DBEntities : DbContext
    {
        public BdSofts_WebApi_Auth_Blood_DBEntities()
            : base("name=BdSofts_WebApi_Auth_Blood_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blood_UserInfo> Blood_UserInfo { get; set; }
    }
}
